/**
 * Comprehensive demo data based on actual GSU Nutrislice menu items.
 * This provides rich data for demos when backend/Supabase is not available.
 */

export interface Dish {
  dish_id: number;
  name: string;
  description: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  saturated_fat?: number;
  trans_fat?: number;
  cholesterol?: number;
  sodium?: number;
  fiber?: number;
  sugar?: number;
  vitamin_d?: number;
  serving_size: string;
  ingredients: string;
  allergens: string[];
  dietary_tags: string[];
  contains_pork: boolean;
  venue_id: number;
  venue_name: string;
  meal_type: 'breakfast' | 'lunch' | 'dinner';
  image_url?: string;
  avg_rating: number;
  review_count: number;
}

export interface Venue {
  venue_id: number;
  name: string;
  location: string;
  description: string;
  hours: {
    breakfast?: string;
    lunch?: string;
    dinner?: string;
  };
  image_url?: string;
}

// GSU Dining Venues
export const venues: Venue[] = [
  {
    venue_id: 1,
    name: "Patton Hall",
    location: "75 Piedmont Ave NE",
    description: "Main residential dining hall offering diverse cuisine options including Southern comfort food, international dishes, and healthy alternatives.",
    hours: {
      breakfast: "7:00 AM - 10:00 AM",
      lunch: "11:00 AM - 2:00 PM", 
      dinner: "5:00 PM - 8:00 PM"
    }
  },
  {
    venue_id: 2,
    name: "The Commons",
    location: "Student Center",
    description: "Food court style dining with multiple stations including pizza, grill, salad bar, and daily specials.",
    hours: {
      breakfast: "7:30 AM - 10:30 AM",
      lunch: "10:30 AM - 3:00 PM",
      dinner: "5:00 PM - 9:00 PM"
    }
  },
  {
    venue_id: 3,
    name: "Piedmont North",
    location: "Piedmont North Building",
    description: "Residential dining featuring fresh-made entrees, a salad bar, and grab-and-go options.",
    hours: {
      breakfast: "7:00 AM - 10:00 AM",
      lunch: "11:00 AM - 2:00 PM",
      dinner: "5:00 PM - 8:00 PM"
    }
  }
];

// Comprehensive dish data based on GSU Nutrislice menus
export const dishes: Dish[] = [
  // Breakfast Items - from Patton Hall screenshots
  {
    dish_id: 1,
    name: "Crispy Bacon",
    description: "Classic crispy bacon strips, perfectly cooked",
    calories: 120,
    protein: 9,
    carbs: 1,
    fat: 9,
    saturated_fat: 3,
    trans_fat: 0,
    cholesterol: 25,
    sodium: 450,
    fiber: 0,
    sugar: 0,
    serving_size: "2 each",
    ingredients: "Pork Bacon (Cured with Water, Salt, Sugar, Sodium Phosphate, Sodium Erythorbate, Sodium Nitrite)",
    allergens: [],
    dietary_tags: ["high-protein"],
    contains_pork: true,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "breakfast",
    avg_rating: 4.2,
    review_count: 45
  },
  {
    dish_id: 2,
    name: "Flaky Buttermilk Biscuits",
    description: "Southern-style flaky biscuits with solid parchment margarine",
    calories: 225,
    protein: 4,
    carbs: 24,
    fat: 12,
    saturated_fat: 2.8,
    trans_fat: 0,
    cholesterol: 0,
    sodium: 628,
    fiber: 1,
    sugar: 2,
    vitamin_d: 107,
    serving_size: "1 each",
    ingredients: "Southern Style Biscuits, Solid Parchment Margarine",
    allergens: ["milk", "wheat", "soy"],
    dietary_tags: ["vegetarian"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "breakfast",
    avg_rating: 4.5,
    review_count: 78
  },
  {
    dish_id: 3,
    name: "Hardboiled Eggs",
    description: "Fresh hardboiled eggs, a great protein source",
    calories: 70,
    protein: 6,
    carbs: 0,
    fat: 5,
    saturated_fat: 1.5,
    cholesterol: 185,
    sodium: 70,
    fiber: 0,
    sugar: 0,
    serving_size: "1 each",
    ingredients: "Eggs",
    allergens: ["eggs"],
    dietary_tags: ["vegetarian", "gluten-free", "high-protein"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "breakfast",
    avg_rating: 4.0,
    review_count: 32
  },
  {
    dish_id: 4,
    name: "Pork Sausage Links",
    description: "Classic breakfast pork sausage links",
    calories: 170,
    protein: 7,
    carbs: 0,
    fat: 15,
    saturated_fat: 5,
    cholesterol: 35,
    sodium: 380,
    fiber: 0,
    sugar: 0,
    serving_size: "2 each",
    ingredients: "Pork, Water, Salt, Spices, Dextrose, Monosodium Glutamate",
    allergens: [],
    dietary_tags: ["high-protein"],
    contains_pork: true,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "breakfast",
    avg_rating: 4.1,
    review_count: 41
  },
  {
    dish_id: 5,
    name: "Turkey Bacon",
    description: "Leaner turkey bacon alternative, crispy and delicious",
    calories: 60,
    protein: 5,
    carbs: 1,
    fat: 4,
    saturated_fat: 1,
    cholesterol: 25,
    sodium: 300,
    fiber: 0,
    sugar: 0,
    serving_size: "2 each",
    ingredients: "Turkey, Water, Salt, Sugar, Smoke Flavoring, Sodium Phosphate",
    allergens: [],
    dietary_tags: ["high-protein", "halal"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "breakfast",
    avg_rating: 4.3,
    review_count: 56
  },
  {
    dish_id: 6,
    name: "Turkey Sausage Patty",
    description: "Lean turkey sausage patty, great pork-free alternative",
    calories: 80,
    protein: 10,
    carbs: 3,
    fat: 3,
    saturated_fat: 1,
    cholesterol: 40,
    sodium: 320,
    fiber: 0,
    sugar: 0,
    serving_size: "2 each",
    ingredients: "Turkey, Water, Contains 2% or less: Salt, Sugar, Spices, Onion Powder, Garlic Powder",
    allergens: [],
    dietary_tags: ["high-protein", "halal"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "breakfast",
    avg_rating: 4.4,
    review_count: 39
  },
  {
    dish_id: 7,
    name: "Chicken Sausage Patties",
    description: "Savory chicken sausage patties with herbs and spices",
    calories: 110,
    protein: 12,
    carbs: 2,
    fat: 6,
    saturated_fat: 2,
    cholesterol: 50,
    sodium: 350,
    fiber: 0,
    sugar: 1,
    serving_size: "2 each",
    ingredients: "Chicken, Water, Salt, Spices, Sugar, Garlic Powder",
    allergens: [],
    dietary_tags: ["high-protein", "halal"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "breakfast",
    avg_rating: 4.2,
    review_count: 28
  },
  {
    dish_id: 8,
    name: "Scrambled Eggs",
    description: "Fluffy scrambled eggs made fresh",
    calories: 90,
    protein: 6,
    carbs: 2,
    fat: 7,
    saturated_fat: 2,
    cholesterol: 185,
    sodium: 150,
    fiber: 0,
    sugar: 0,
    serving_size: "4 oz",
    ingredients: "Eggs, Milk, Butter, Salt, Pepper",
    allergens: ["eggs", "milk"],
    dietary_tags: ["vegetarian", "gluten-free"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "breakfast",
    avg_rating: 4.0,
    review_count: 52
  },
  {
    dish_id: 9,
    name: "Southern Style Grits",
    description: "Creamy Southern-style grits with butter",
    calories: 110,
    protein: 2,
    carbs: 18,
    fat: 3,
    saturated_fat: 1.5,
    cholesterol: 5,
    sodium: 280,
    fiber: 1,
    sugar: 0,
    serving_size: "4 oz",
    ingredients: "Enriched White Corn Grits, Butter, Salt, Water",
    allergens: ["milk"],
    dietary_tags: ["vegetarian", "gluten-free"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "breakfast",
    avg_rating: 4.3,
    review_count: 67
  },
  {
    dish_id: 10,
    name: "Sawmill Gravy",
    description: "Traditional Southern sawmill gravy, perfect for biscuits",
    calories: 80,
    protein: 2,
    carbs: 5,
    fat: 6,
    saturated_fat: 2,
    cholesterol: 10,
    sodium: 320,
    fiber: 0,
    sugar: 1,
    serving_size: "2 oz",
    ingredients: "Milk, Flour, Butter, Salt, Black Pepper",
    allergens: ["milk", "wheat", "soy"],
    dietary_tags: ["vegetarian"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "breakfast",
    avg_rating: 4.6,
    review_count: 89
  },
  {
    dish_id: 11,
    name: "Cinnamon French Toast Sticks",
    description: "Sweet cinnamon-dusted French toast sticks",
    calories: 180,
    protein: 5,
    carbs: 28,
    fat: 5,
    saturated_fat: 1,
    cholesterol: 40,
    sodium: 280,
    fiber: 1,
    sugar: 8,
    serving_size: "4 each",
    ingredients: "Enriched Bread, Eggs, Milk, Cinnamon, Sugar, Vanilla Extract",
    allergens: ["eggs", "milk", "wheat", "soy"],
    dietary_tags: ["vegetarian"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "breakfast",
    avg_rating: 4.7,
    review_count: 102
  },
  {
    dish_id: 12,
    name: "Potatoes O'Brien",
    description: "Diced potatoes with peppers and onions",
    calories: 140,
    protein: 2,
    carbs: 22,
    fat: 5,
    saturated_fat: 0.5,
    cholesterol: 0,
    sodium: 380,
    fiber: 3,
    sugar: 2,
    serving_size: "4 oz",
    ingredients: "Potatoes, Bell Peppers, Onions, Vegetable Oil, Salt, Pepper",
    allergens: [],
    dietary_tags: ["vegan", "gluten-free"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "breakfast",
    avg_rating: 4.2,
    review_count: 58
  },
  {
    dish_id: 13,
    name: "Apple Cinnamon Muffin",
    description: "Freshly baked apple cinnamon muffin",
    calories: 320,
    protein: 4,
    carbs: 52,
    fat: 11,
    saturated_fat: 2,
    cholesterol: 35,
    sodium: 290,
    fiber: 1,
    sugar: 28,
    serving_size: "1 each",
    ingredients: "Flour, Sugar, Apples, Butter, Eggs, Cinnamon, Baking Powder",
    allergens: ["eggs", "milk", "wheat"],
    dietary_tags: ["vegetarian"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "breakfast",
    avg_rating: 4.4,
    review_count: 73
  },
  {
    dish_id: 14,
    name: "Blueberry Muffin",
    description: "Moist blueberry muffin with real blueberries",
    calories: 340,
    protein: 4,
    carbs: 54,
    fat: 12,
    saturated_fat: 2.5,
    cholesterol: 40,
    sodium: 310,
    fiber: 1,
    sugar: 30,
    serving_size: "1 each",
    ingredients: "Flour, Sugar, Blueberries, Butter, Eggs, Baking Powder",
    allergens: ["eggs", "milk", "wheat"],
    dietary_tags: ["vegetarian"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "breakfast",
    avg_rating: 4.5,
    review_count: 81
  },
  {
    dish_id: 15,
    name: "Egg White Frittata",
    description: "Healthy egg white frittata with vegetables",
    calories: 90,
    protein: 12,
    carbs: 3,
    fat: 3,
    saturated_fat: 1,
    cholesterol: 0,
    sodium: 220,
    fiber: 1,
    sugar: 1,
    serving_size: "3 oz",
    ingredients: "Egg Whites, Bell Peppers, Spinach, Onions, Low-Fat Cheese",
    allergens: ["eggs", "milk"],
    dietary_tags: ["vegetarian", "gluten-free", "high-protein"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "breakfast",
    avg_rating: 4.1,
    review_count: 34
  },
  {
    dish_id: 16,
    name: "Fruit & Cashew Granola Bars",
    description: "Nutritious granola bars with dried fruit and cashews",
    calories: 200,
    protein: 4,
    carbs: 45,
    fat: 7,
    saturated_fat: 1,
    cholesterol: 0,
    sodium: 150,
    fiber: 5,
    sugar: 18,
    serving_size: "1 each",
    ingredients: "Oats, Honey, Cashews, Dried Cranberries, Dried Apricots, Brown Rice Syrup",
    allergens: ["tree_nuts"],
    dietary_tags: ["vegetarian", "high-fiber"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "breakfast",
    avg_rating: 4.3,
    review_count: 47
  },
  {
    dish_id: 17,
    name: "Just Egg Scrambled Eggs",
    description: "Plant-based scrambled eggs made with Just Egg",
    calories: 70,
    protein: 5,
    carbs: 1,
    fat: 5,
    saturated_fat: 0,
    cholesterol: 0,
    sodium: 170,
    fiber: 0,
    sugar: 0,
    serving_size: "4 oz",
    ingredients: "Mung Bean Protein Isolate, Expeller-Pressed Canola Oil, Water, Contains less than 2% of: Onion Puree, Turmeric",
    allergens: [],
    dietary_tags: ["vegan", "gluten-free", "high-protein"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "breakfast",
    avg_rating: 4.0,
    review_count: 29
  },
  {
    dish_id: 18,
    name: "Overnight Oats",
    description: "Creamy overnight oats with fresh toppings",
    calories: 280,
    protein: 8,
    carbs: 48,
    fat: 6,
    saturated_fat: 1,
    cholesterol: 0,
    sodium: 120,
    fiber: 6,
    sugar: 12,
    serving_size: "1 oz",
    ingredients: "Rolled Oats, Oat Milk, Chia Seeds, Maple Syrup, Vanilla Extract",
    allergens: [],
    dietary_tags: ["vegan", "high-fiber"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "breakfast",
    avg_rating: 4.4,
    review_count: 52
  },
  {
    dish_id: 19,
    name: "Plant-Based Breakfast Sausage",
    description: "Delicious plant-based sausage patty, tastes like the real thing",
    calories: 90,
    protein: 10,
    carbs: 7,
    fat: 3,
    saturated_fat: 0.5,
    cholesterol: 0,
    sodium: 350,
    fiber: 3,
    sugar: 0,
    serving_size: "2 each",
    ingredients: "Water, Soy Protein Concentrate, Coconut Oil, Sunflower Oil, Natural Flavors",
    allergens: ["soy"],
    dietary_tags: ["vegan", "high-protein"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "breakfast",
    avg_rating: 4.2,
    review_count: 38
  },
  {
    dish_id: 20,
    name: "Almonds",
    description: "Whole roasted almonds, a healthy snack option",
    calories: 170,
    protein: 6,
    carbs: 6,
    fat: 15,
    saturated_fat: 1,
    cholesterol: 0,
    sodium: 0,
    fiber: 4,
    sugar: 1,
    serving_size: "1 oz",
    ingredients: "Almonds",
    allergens: ["tree_nuts"],
    dietary_tags: ["vegan", "gluten-free", "high-fiber"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "breakfast",
    avg_rating: 4.1,
    review_count: 25
  },
  {
    dish_id: 21,
    name: "Fresh Apples",
    description: "Crisp fresh apples, a healthy fruit option",
    calories: 95,
    protein: 0,
    carbs: 25,
    fat: 0,
    saturated_fat: 0,
    cholesterol: 0,
    sodium: 0,
    fiber: 4,
    sugar: 19,
    serving_size: "1 each",
    ingredients: "Fresh Apple",
    allergens: [],
    dietary_tags: ["vegan", "gluten-free", "high-fiber"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "breakfast",
    avg_rating: 4.5,
    review_count: 31
  },
  // Lunch/Dinner items
  {
    dish_id: 22,
    name: "Grilled Chicken Breast",
    description: "Seasoned grilled chicken breast, lean and protein-packed",
    calories: 180,
    protein: 35,
    carbs: 0,
    fat: 4,
    saturated_fat: 1,
    cholesterol: 85,
    sodium: 320,
    fiber: 0,
    sugar: 0,
    serving_size: "4 oz",
    ingredients: "Chicken Breast, Olive Oil, Garlic, Salt, Pepper, Italian Herbs",
    allergens: [],
    dietary_tags: ["gluten-free", "high-protein", "halal"],
    contains_pork: false,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "lunch",
    avg_rating: 4.6,
    review_count: 124
  },
  {
    dish_id: 23,
    name: "Impossible Burger",
    description: "Plant-based burger that looks, cooks, and tastes like beef",
    calories: 240,
    protein: 19,
    carbs: 9,
    fat: 14,
    saturated_fat: 8,
    cholesterol: 0,
    sodium: 370,
    fiber: 3,
    sugar: 0,
    serving_size: "1 patty",
    ingredients: "Water, Soy Protein Concentrate, Coconut Oil, Sunflower Oil, Natural Flavors, Potato Protein",
    allergens: ["soy"],
    dietary_tags: ["vegetarian", "high-protein"],
    contains_pork: false,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "lunch",
    avg_rating: 4.5,
    review_count: 89
  },
  {
    dish_id: 24,
    name: "Beyond Sausage",
    description: "Plant-based sausage with authentic smoky flavor",
    calories: 190,
    protein: 16,
    carbs: 4,
    fat: 12,
    saturated_fat: 5,
    cholesterol: 0,
    sodium: 450,
    fiber: 2,
    sugar: 0,
    serving_size: "1 link",
    ingredients: "Water, Pea Protein, Refined Coconut Oil, Sunflower Oil, Natural Flavors",
    allergens: [],
    dietary_tags: ["vegan", "gluten-free", "high-protein"],
    contains_pork: false,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "lunch",
    avg_rating: 4.3,
    review_count: 67
  },
  {
    dish_id: 25,
    name: "Pepperoni Pizza",
    description: "Classic pepperoni pizza with mozzarella cheese",
    calories: 280,
    protein: 12,
    carbs: 32,
    fat: 12,
    saturated_fat: 5,
    cholesterol: 30,
    sodium: 620,
    fiber: 2,
    sugar: 3,
    serving_size: "1 slice",
    ingredients: "Enriched Flour, Tomato Sauce, Mozzarella Cheese, Pepperoni (Pork, Beef, Salt, Spices)",
    allergens: ["milk", "wheat"],
    dietary_tags: [],
    contains_pork: true,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "lunch",
    avg_rating: 4.4,
    review_count: 156
  },
  {
    dish_id: 26,
    name: "Cheese Pizza",
    description: "Classic cheese pizza with tomato sauce and mozzarella",
    calories: 230,
    protein: 10,
    carbs: 30,
    fat: 8,
    saturated_fat: 4,
    cholesterol: 20,
    sodium: 480,
    fiber: 2,
    sugar: 3,
    serving_size: "1 slice",
    ingredients: "Enriched Flour, Tomato Sauce, Mozzarella Cheese, Olive Oil, Italian Herbs",
    allergens: ["milk", "wheat"],
    dietary_tags: ["vegetarian"],
    contains_pork: false,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "lunch",
    avg_rating: 4.3,
    review_count: 134
  },
  {
    dish_id: 27,
    name: "Garden Salad",
    description: "Fresh mixed greens with vegetables and choice of dressing",
    calories: 45,
    protein: 2,
    carbs: 8,
    fat: 1,
    saturated_fat: 0,
    cholesterol: 0,
    sodium: 25,
    fiber: 3,
    sugar: 4,
    serving_size: "4 oz",
    ingredients: "Mixed Greens, Tomatoes, Cucumbers, Carrots, Red Onion",
    allergens: [],
    dietary_tags: ["vegan", "gluten-free", "high-fiber"],
    contains_pork: false,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "lunch",
    avg_rating: 4.0,
    review_count: 78
  },
  {
    dish_id: 28,
    name: "Falafel Wrap",
    description: "Crispy falafel with hummus, vegetables in a warm pita",
    calories: 380,
    protein: 14,
    carbs: 52,
    fat: 14,
    saturated_fat: 2,
    cholesterol: 0,
    sodium: 680,
    fiber: 8,
    sugar: 4,
    serving_size: "1 wrap",
    ingredients: "Pita Bread, Falafel (Chickpeas, Onion, Garlic, Herbs), Hummus, Lettuce, Tomato, Tahini Sauce",
    allergens: ["wheat", "sesame"],
    dietary_tags: ["vegan", "high-fiber", "halal"],
    contains_pork: false,
    venue_id: 3,
    venue_name: "Piedmont North",
    meal_type: "lunch",
    avg_rating: 4.6,
    review_count: 92
  },
  {
    dish_id: 29,
    name: "Chicken Tikka Masala",
    description: "Tender chicken in creamy, spiced tomato sauce",
    calories: 320,
    protein: 28,
    carbs: 12,
    fat: 18,
    saturated_fat: 6,
    cholesterol: 95,
    sodium: 720,
    fiber: 2,
    sugar: 6,
    serving_size: "6 oz",
    ingredients: "Chicken, Tomatoes, Cream, Yogurt, Garam Masala, Ginger, Garlic, Cumin",
    allergens: ["milk"],
    dietary_tags: ["gluten-free", "high-protein", "halal"],
    contains_pork: false,
    venue_id: 3,
    venue_name: "Piedmont North",
    meal_type: "dinner",
    avg_rating: 4.7,
    review_count: 108
  },
  {
    dish_id: 30,
    name: "Vegetable Stir Fry",
    description: "Wok-tossed vegetables with soy ginger sauce",
    calories: 160,
    protein: 5,
    carbs: 22,
    fat: 6,
    saturated_fat: 1,
    cholesterol: 0,
    sodium: 580,
    fiber: 4,
    sugar: 8,
    serving_size: "6 oz",
    ingredients: "Broccoli, Bell Peppers, Snap Peas, Carrots, Mushrooms, Soy Sauce, Ginger, Garlic, Sesame Oil",
    allergens: ["soy", "sesame"],
    dietary_tags: ["vegan", "high-fiber"],
    contains_pork: false,
    venue_id: 3,
    venue_name: "Piedmont North",
    meal_type: "dinner",
    avg_rating: 4.2,
    review_count: 76
  },
  // SPICY DISHES
  {
    dish_id: 31,
    name: "Buffalo Chicken Wings",
    description: "Crispy wings tossed in spicy buffalo sauce with blue cheese",
    calories: 480,
    protein: 32,
    carbs: 8,
    fat: 36,
    saturated_fat: 10,
    cholesterol: 120,
    sodium: 1200,
    fiber: 0,
    sugar: 2,
    serving_size: "6 wings",
    ingredients: "Chicken Wings, Buffalo Hot Sauce, Butter, Cayenne Pepper, Vinegar, Garlic",
    allergens: ["milk"],
    dietary_tags: ["high-protein", "gluten-free", "spicy"],
    contains_pork: false,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "lunch",
    avg_rating: 4.6,
    review_count: 156
  },
  {
    dish_id: 32,
    name: "Spicy Korean BBQ Beef",
    description: "Gochujang-marinated beef with spicy kick, served with rice",
    calories: 520,
    protein: 35,
    carbs: 42,
    fat: 22,
    saturated_fat: 8,
    cholesterol: 85,
    sodium: 890,
    fiber: 2,
    sugar: 12,
    serving_size: "8 oz",
    ingredients: "Beef Sirloin, Gochujang, Soy Sauce, Sesame Oil, Korean Chili Flakes, Garlic, Ginger, Rice",
    allergens: ["soy", "sesame", "wheat"],
    dietary_tags: ["high-protein", "spicy"],
    contains_pork: false,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "dinner",
    avg_rating: 4.8,
    review_count: 203
  },
  {
    dish_id: 33,
    name: "Cajun Shrimp & Grits",
    description: "Spicy Cajun shrimp over creamy stone-ground grits",
    calories: 450,
    protein: 28,
    carbs: 38,
    fat: 20,
    saturated_fat: 8,
    cholesterol: 180,
    sodium: 980,
    fiber: 2,
    sugar: 3,
    serving_size: "10 oz",
    ingredients: "Shrimp, Stone Ground Grits, Cajun Seasoning, Cayenne, Andouille Sausage, Bell Peppers, Cream, Butter",
    allergens: ["shellfish", "milk"],
    dietary_tags: ["gluten-free", "high-protein", "spicy"],
    contains_pork: true,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "dinner",
    avg_rating: 4.7,
    review_count: 134
  },
  {
    dish_id: 34,
    name: "Jalapeño Cheddar Burger",
    description: "Beef patty with jalapeños, pepper jack cheese, and sriracha mayo",
    calories: 680,
    protein: 38,
    carbs: 42,
    fat: 42,
    saturated_fat: 16,
    cholesterol: 110,
    sodium: 1050,
    fiber: 2,
    sugar: 6,
    serving_size: "1 burger",
    ingredients: "Beef Patty, Jalapeños, Pepper Jack Cheese, Sriracha Mayo, Lettuce, Tomato, Brioche Bun",
    allergens: ["milk", "wheat", "eggs"],
    dietary_tags: ["high-protein", "spicy"],
    contains_pork: false,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "lunch",
    avg_rating: 4.5,
    review_count: 189
  },
  // OMEGA-3 RICH FISH DISHES
  {
    dish_id: 35,
    name: "Grilled Atlantic Salmon",
    description: "Heart-healthy salmon fillet with lemon herb butter, rich in omega-3s",
    calories: 380,
    protein: 42,
    carbs: 2,
    fat: 22,
    saturated_fat: 5,
    cholesterol: 95,
    sodium: 420,
    fiber: 0,
    sugar: 0,
    serving_size: "6 oz fillet",
    ingredients: "Atlantic Salmon, Olive Oil, Lemon, Dill, Parsley, Garlic, Butter",
    allergens: ["fish", "milk"],
    dietary_tags: ["gluten-free", "high-protein", "omega-3", "keto"],
    contains_pork: false,
    venue_id: 3,
    venue_name: "Piedmont North",
    meal_type: "dinner",
    avg_rating: 4.8,
    review_count: 167
  },
  {
    dish_id: 36,
    name: "Ahi Tuna Poke Bowl",
    description: "Fresh ahi tuna with avocado, edamame, and sesame, packed with omega-3s",
    calories: 420,
    protein: 35,
    carbs: 38,
    fat: 16,
    saturated_fat: 3,
    cholesterol: 55,
    sodium: 680,
    fiber: 6,
    sugar: 4,
    serving_size: "12 oz bowl",
    ingredients: "Ahi Tuna, Sushi Rice, Avocado, Edamame, Seaweed Salad, Sesame Seeds, Soy Sauce, Sriracha Mayo",
    allergens: ["fish", "soy", "sesame"],
    dietary_tags: ["high-protein", "omega-3"],
    contains_pork: false,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "lunch",
    avg_rating: 4.7,
    review_count: 142
  },
  {
    dish_id: 37,
    name: "Baked Cod with Vegetables",
    description: "Flaky white fish with roasted vegetables, high in omega-3s and protein",
    calories: 290,
    protein: 34,
    carbs: 18,
    fat: 10,
    saturated_fat: 2,
    cholesterol: 75,
    sodium: 380,
    fiber: 4,
    sugar: 5,
    serving_size: "8 oz",
    ingredients: "Atlantic Cod, Zucchini, Cherry Tomatoes, Asparagus, Olive Oil, Lemon, Herbs",
    allergens: ["fish"],
    dietary_tags: ["gluten-free", "high-protein", "omega-3", "low-calorie"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "dinner",
    avg_rating: 4.4,
    review_count: 89
  },
  // HIGH PROTEIN BREAKFAST FOR BODYBUILDERS
  {
    dish_id: 38,
    name: "Bodybuilder's Power Breakfast",
    description: "6 egg whites, turkey sausage, avocado, and oats - 50g protein!",
    calories: 520,
    protein: 52,
    carbs: 35,
    fat: 20,
    saturated_fat: 4,
    cholesterol: 85,
    sodium: 720,
    fiber: 8,
    sugar: 3,
    serving_size: "Full plate",
    ingredients: "Egg Whites, Turkey Sausage, Avocado, Steel Cut Oats, Spinach, Tomatoes",
    allergens: ["eggs"],
    dietary_tags: ["gluten-free", "high-protein", "muscle-building"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "breakfast",
    avg_rating: 4.9,
    review_count: 234
  },
  {
    dish_id: 39,
    name: "Protein Pancake Stack",
    description: "Whey-enhanced pancakes with Greek yogurt and berries - 35g protein",
    calories: 480,
    protein: 35,
    carbs: 52,
    fat: 14,
    saturated_fat: 3,
    cholesterol: 65,
    sodium: 520,
    fiber: 4,
    sugar: 18,
    serving_size: "3 pancakes",
    ingredients: "Whole Wheat Flour, Whey Protein, Eggs, Greek Yogurt, Blueberries, Maple Syrup",
    allergens: ["milk", "wheat", "eggs"],
    dietary_tags: ["vegetarian", "high-protein", "muscle-building"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "breakfast",
    avg_rating: 4.6,
    review_count: 178
  },
  {
    dish_id: 40,
    name: "Steak & Eggs Platter",
    description: "8oz sirloin with 3 eggs any style - ultimate muscle fuel (55g protein)",
    calories: 680,
    protein: 55,
    carbs: 4,
    fat: 48,
    saturated_fat: 18,
    cholesterol: 520,
    sodium: 890,
    fiber: 0,
    sugar: 0,
    serving_size: "Full plate",
    ingredients: "USDA Choice Sirloin Steak, Eggs, Butter, Seasoning, Fresh Herbs",
    allergens: ["eggs", "milk"],
    dietary_tags: ["gluten-free", "high-protein", "keto", "muscle-building"],
    contains_pork: false,
    venue_id: 3,
    venue_name: "Piedmont North",
    meal_type: "breakfast",
    avg_rating: 4.8,
    review_count: 267
  },
  {
    dish_id: 41,
    name: "Thai Basil Chicken (Spicy)",
    description: "Wok-fried chicken with Thai chilies, basil, and garlic - authentic heat!",
    calories: 380,
    protein: 32,
    carbs: 28,
    fat: 16,
    saturated_fat: 4,
    cholesterol: 85,
    sodium: 920,
    fiber: 2,
    sugar: 6,
    serving_size: "8 oz with rice",
    ingredients: "Chicken Breast, Thai Basil, Thai Bird Chilies, Garlic, Fish Sauce, Oyster Sauce, Jasmine Rice",
    allergens: ["fish", "soy"],
    dietary_tags: ["high-protein", "spicy"],
    contains_pork: false,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "dinner",
    avg_rating: 4.6,
    review_count: 145
  },
  // KOSHER dishes
  {
    dish_id: 42,
    name: "Kosher Grilled Salmon",
    description: "Wild-caught salmon with lemon herb seasoning, prepared under kosher supervision",
    calories: 320,
    protein: 34,
    carbs: 2,
    fat: 18,
    saturated_fat: 3,
    cholesterol: 80,
    sodium: 280,
    fiber: 0,
    sugar: 0,
    serving_size: "6 oz",
    ingredients: "Wild Salmon, Olive Oil, Lemon, Fresh Herbs, Sea Salt",
    allergens: ["fish"],
    dietary_tags: ["kosher", "high-protein", "gluten-free", "low-carb"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "dinner",
    avg_rating: 4.7,
    review_count: 89
  },
  {
    dish_id: 43,
    name: "Kosher Roasted Chicken",
    description: "Traditional roasted chicken quarter with herbs, kosher certified",
    calories: 290,
    protein: 32,
    carbs: 0,
    fat: 16,
    saturated_fat: 4,
    cholesterol: 95,
    sodium: 320,
    fiber: 0,
    sugar: 0,
    serving_size: "1 quarter",
    ingredients: "Chicken Quarter, Kosher Salt, Rosemary, Thyme, Garlic",
    allergens: [],
    dietary_tags: ["kosher", "high-protein", "gluten-free", "low-carb"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "lunch",
    avg_rating: 4.5,
    review_count: 67
  },
  {
    dish_id: 44,
    name: "Kosher Vegetable Soup",
    description: "Hearty vegetable soup made with kosher ingredients, no meat",
    calories: 120,
    protein: 4,
    carbs: 22,
    fat: 2,
    saturated_fat: 0,
    cholesterol: 0,
    sodium: 380,
    fiber: 5,
    sugar: 6,
    serving_size: "8 oz",
    ingredients: "Carrots, Celery, Onions, Potatoes, Tomatoes, Vegetable Broth, Herbs",
    allergens: [],
    dietary_tags: ["kosher", "vegan", "gluten-free", "low-carb"],
    contains_pork: false,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "lunch",
    avg_rating: 4.3,
    review_count: 45
  },
  // LOW-CARB dishes
  {
    dish_id: 45,
    name: "Keto Bacon Cheeseburger Bowl",
    description: "Seasoned beef patty with bacon, cheese, lettuce, tomato - no bun",
    calories: 480,
    protein: 38,
    carbs: 6,
    fat: 34,
    saturated_fat: 14,
    cholesterol: 120,
    sodium: 680,
    fiber: 2,
    sugar: 3,
    serving_size: "10 oz",
    ingredients: "Ground Beef, Bacon, Cheddar Cheese, Lettuce, Tomato, Pickles, Special Sauce",
    allergens: ["milk"],
    dietary_tags: ["low-carb", "keto", "high-protein", "gluten-free"],
    contains_pork: true,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "lunch",
    avg_rating: 4.6,
    review_count: 112
  },
  {
    dish_id: 46,
    name: "Grilled Chicken Caesar Salad",
    description: "Romaine lettuce with grilled chicken, parmesan, and caesar dressing - no croutons",
    calories: 340,
    protein: 32,
    carbs: 8,
    fat: 20,
    saturated_fat: 5,
    cholesterol: 85,
    sodium: 520,
    fiber: 3,
    sugar: 2,
    serving_size: "12 oz",
    ingredients: "Romaine Lettuce, Grilled Chicken Breast, Parmesan, Caesar Dressing",
    allergens: ["milk", "eggs", "fish"],
    dietary_tags: ["low-carb", "high-protein", "gluten-free"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "lunch",
    avg_rating: 4.4,
    review_count: 156
  },
  {
    dish_id: 47,
    name: "Cauliflower Fried Rice",
    description: "Riced cauliflower stir-fried with eggs, vegetables, and sesame oil",
    calories: 180,
    protein: 12,
    carbs: 12,
    fat: 10,
    saturated_fat: 2,
    cholesterol: 95,
    sodium: 420,
    fiber: 4,
    sugar: 4,
    serving_size: "8 oz",
    ingredients: "Cauliflower Rice, Eggs, Peas, Carrots, Green Onion, Sesame Oil, Soy Sauce",
    allergens: ["eggs", "soy", "sesame"],
    dietary_tags: ["low-carb", "vegetarian", "gluten-free"],
    contains_pork: false,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "dinner",
    avg_rating: 4.2,
    review_count: 78
  },
  // DAIRY-FREE dishes
  {
    dish_id: 48,
    name: "Coconut Curry Chicken",
    description: "Thai-style chicken curry with coconut milk, vegetables, and jasmine rice",
    calories: 420,
    protein: 28,
    carbs: 38,
    fat: 18,
    saturated_fat: 12,
    cholesterol: 75,
    sodium: 580,
    fiber: 3,
    sugar: 5,
    serving_size: "10 oz",
    ingredients: "Chicken Breast, Coconut Milk, Curry Paste, Bell Peppers, Bamboo Shoots, Jasmine Rice",
    allergens: [],
    dietary_tags: ["dairy-free", "gluten-free", "high-protein"],
    contains_pork: false,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "dinner",
    avg_rating: 4.5,
    review_count: 134
  },
  {
    dish_id: 49,
    name: "Mediterranean Quinoa Bowl",
    description: "Fluffy quinoa with chickpeas, cucumber, tomatoes, olives, and lemon tahini dressing",
    calories: 380,
    protein: 14,
    carbs: 52,
    fat: 14,
    saturated_fat: 2,
    cholesterol: 0,
    sodium: 420,
    fiber: 9,
    sugar: 6,
    serving_size: "12 oz",
    ingredients: "Quinoa, Chickpeas, Cucumber, Tomatoes, Kalamata Olives, Red Onion, Tahini, Lemon",
    allergens: ["sesame"],
    dietary_tags: ["dairy-free", "vegan", "high-fiber"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "lunch",
    avg_rating: 4.6,
    review_count: 98
  },
  {
    dish_id: 50,
    name: "Teriyaki Tofu Stir Fry",
    description: "Crispy tofu with broccoli, snap peas, and carrots in teriyaki sauce",
    calories: 320,
    protein: 18,
    carbs: 36,
    fat: 12,
    saturated_fat: 2,
    cholesterol: 0,
    sodium: 680,
    fiber: 6,
    sugar: 14,
    serving_size: "10 oz",
    ingredients: "Firm Tofu, Broccoli, Snap Peas, Carrots, Teriyaki Sauce, Brown Rice",
    allergens: ["soy", "wheat"],
    dietary_tags: ["dairy-free", "vegan", "high-fiber"],
    contains_pork: false,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "dinner",
    avg_rating: 4.3,
    review_count: 87
  },
  // LOW-SODIUM dishes
  {
    dish_id: 51,
    name: "Herb Roasted Turkey Breast",
    description: "Sliced turkey breast with fresh herbs, minimal salt - heart healthy",
    calories: 160,
    protein: 32,
    carbs: 0,
    fat: 3,
    saturated_fat: 1,
    cholesterol: 70,
    sodium: 140,
    fiber: 0,
    sugar: 0,
    serving_size: "4 oz",
    ingredients: "Turkey Breast, Rosemary, Thyme, Sage, Black Pepper, Olive Oil",
    allergens: [],
    dietary_tags: ["low-sodium", "high-protein", "gluten-free", "low-carb"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "lunch",
    avg_rating: 4.2,
    review_count: 56
  },
  {
    dish_id: 52,
    name: "Fresh Fruit Plate",
    description: "Seasonal fresh fruits - naturally low sodium and refreshing",
    calories: 120,
    protein: 2,
    carbs: 30,
    fat: 0,
    saturated_fat: 0,
    cholesterol: 0,
    sodium: 5,
    fiber: 5,
    sugar: 22,
    serving_size: "8 oz",
    ingredients: "Strawberries, Blueberries, Cantaloupe, Honeydew, Grapes",
    allergens: [],
    dietary_tags: ["low-sodium", "vegan", "gluten-free", "high-fiber"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "breakfast",
    avg_rating: 4.7,
    review_count: 189
  },
  {
    dish_id: 53,
    name: "Steamed Vegetables Medley",
    description: "Fresh steamed broccoli, carrots, and zucchini with lemon - no added salt",
    calories: 80,
    protein: 4,
    carbs: 16,
    fat: 1,
    saturated_fat: 0,
    cholesterol: 0,
    sodium: 45,
    fiber: 6,
    sugar: 8,
    serving_size: "6 oz",
    ingredients: "Broccoli, Carrots, Zucchini, Lemon, Black Pepper",
    allergens: [],
    dietary_tags: ["low-sodium", "vegan", "gluten-free", "high-fiber", "low-carb"],
    contains_pork: false,
    venue_id: 3,
    venue_name: "Piedmont North",
    meal_type: "dinner",
    avg_rating: 4.0,
    review_count: 42
  },
  // NUT-FREE dishes
  {
    dish_id: 54,
    name: "Classic Beef Tacos",
    description: "Seasoned ground beef with lettuce, cheese, tomato in corn tortillas - nut free facility",
    calories: 340,
    protein: 22,
    carbs: 28,
    fat: 16,
    saturated_fat: 6,
    cholesterol: 55,
    sodium: 520,
    fiber: 3,
    sugar: 3,
    serving_size: "2 tacos",
    ingredients: "Ground Beef, Corn Tortillas, Cheddar Cheese, Lettuce, Tomato, Taco Seasoning",
    allergens: ["milk"],
    dietary_tags: ["nut-free", "gluten-free"],
    contains_pork: false,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "lunch",
    avg_rating: 4.4,
    review_count: 167
  },
  {
    dish_id: 55,
    name: "Spaghetti Marinara",
    description: "Traditional pasta with house-made marinara sauce - prepared in nut-free area",
    calories: 380,
    protein: 12,
    carbs: 72,
    fat: 6,
    saturated_fat: 1,
    cholesterol: 0,
    sodium: 580,
    fiber: 4,
    sugar: 10,
    serving_size: "10 oz",
    ingredients: "Spaghetti Pasta, Tomatoes, Garlic, Basil, Olive Oil, Italian Herbs",
    allergens: ["wheat"],
    dietary_tags: ["nut-free", "vegan", "dairy-free"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "dinner",
    avg_rating: 4.3,
    review_count: 143
  },
  {
    dish_id: 56,
    name: "Sunflower Seed Butter Toast",
    description: "Whole wheat toast with sunflower seed butter - safe peanut/tree nut alternative",
    calories: 260,
    protein: 8,
    carbs: 28,
    fat: 14,
    saturated_fat: 2,
    cholesterol: 0,
    sodium: 280,
    fiber: 4,
    sugar: 6,
    serving_size: "2 slices",
    ingredients: "Whole Wheat Bread, Sunflower Seed Butter",
    allergens: ["wheat"],
    dietary_tags: ["nut-free", "vegan", "dairy-free", "high-fiber"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "breakfast",
    avg_rating: 4.1,
    review_count: 54
  },
  // ==========================================
  // DESSERTS
  // ==========================================
  {
    dish_id: 57,
    name: "Chocolate Lava Cake",
    description: "Warm chocolate cake with molten center, served with vanilla ice cream",
    calories: 450,
    protein: 6,
    carbs: 58,
    fat: 24,
    saturated_fat: 14,
    cholesterol: 120,
    sodium: 180,
    fiber: 2,
    sugar: 42,
    serving_size: "1 cake",
    ingredients: "Dark Chocolate, Butter, Eggs, Sugar, Flour, Vanilla Ice Cream",
    allergens: ["milk", "eggs", "wheat"],
    dietary_tags: ["vegetarian", "dessert"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "dinner",
    avg_rating: 4.9,
    review_count: 234
  },
  {
    dish_id: 58,
    name: "New York Cheesecake",
    description: "Creamy classic cheesecake with graham cracker crust and berry compote",
    calories: 380,
    protein: 7,
    carbs: 32,
    fat: 26,
    saturated_fat: 15,
    cholesterol: 140,
    sodium: 320,
    fiber: 0,
    sugar: 24,
    serving_size: "1 slice",
    ingredients: "Cream Cheese, Sugar, Eggs, Sour Cream, Graham Crackers, Butter, Mixed Berries",
    allergens: ["milk", "eggs", "wheat"],
    dietary_tags: ["vegetarian", "dessert"],
    contains_pork: false,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "dinner",
    avg_rating: 4.8,
    review_count: 189
  },
  {
    dish_id: 59,
    name: "Tiramisu",
    description: "Classic Italian dessert with espresso-soaked ladyfingers and mascarpone cream",
    calories: 320,
    protein: 5,
    carbs: 38,
    fat: 16,
    saturated_fat: 9,
    cholesterol: 95,
    sodium: 120,
    fiber: 0,
    sugar: 28,
    serving_size: "1 piece",
    ingredients: "Mascarpone, Espresso, Ladyfingers, Eggs, Sugar, Cocoa Powder, Kahlua",
    allergens: ["milk", "eggs", "wheat"],
    dietary_tags: ["vegetarian", "dessert", "italian"],
    contains_pork: false,
    venue_id: 3,
    venue_name: "Piedmont North",
    meal_type: "dinner",
    avg_rating: 4.7,
    review_count: 156
  },
  {
    dish_id: 60,
    name: "Apple Pie à la Mode",
    description: "Warm apple pie with cinnamon, topped with vanilla ice cream",
    calories: 420,
    protein: 4,
    carbs: 62,
    fat: 18,
    saturated_fat: 8,
    cholesterol: 45,
    sodium: 280,
    fiber: 3,
    sugar: 38,
    serving_size: "1 slice",
    ingredients: "Apples, Sugar, Cinnamon, Pie Crust, Butter, Vanilla Ice Cream",
    allergens: ["milk", "eggs", "wheat"],
    dietary_tags: ["vegetarian", "dessert"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "dinner",
    avg_rating: 4.6,
    review_count: 178
  },
  {
    dish_id: 61,
    name: "Brownie Sundae",
    description: "Fudgy chocolate brownie with ice cream, hot fudge, and whipped cream",
    calories: 520,
    protein: 7,
    carbs: 68,
    fat: 26,
    saturated_fat: 14,
    cholesterol: 85,
    sodium: 240,
    fiber: 3,
    sugar: 52,
    serving_size: "1 sundae",
    ingredients: "Chocolate Brownie, Vanilla Ice Cream, Hot Fudge, Whipped Cream, Cherries",
    allergens: ["milk", "eggs", "wheat"],
    dietary_tags: ["vegetarian", "dessert"],
    contains_pork: false,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "dinner",
    avg_rating: 4.8,
    review_count: 267
  },
  {
    dish_id: 62,
    name: "Churros with Chocolate",
    description: "Crispy fried dough sticks coated in cinnamon sugar with chocolate dipping sauce",
    calories: 380,
    protein: 4,
    carbs: 52,
    fat: 18,
    saturated_fat: 6,
    cholesterol: 25,
    sodium: 220,
    fiber: 2,
    sugar: 28,
    serving_size: "4 churros",
    ingredients: "Flour, Butter, Eggs, Sugar, Cinnamon, Dark Chocolate",
    allergens: ["milk", "eggs", "wheat"],
    dietary_tags: ["vegetarian", "dessert", "mexican"],
    contains_pork: false,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "dinner",
    avg_rating: 4.7,
    review_count: 198
  },
  {
    dish_id: 63,
    name: "Vegan Chocolate Mousse",
    description: "Rich and creamy dairy-free chocolate mousse made with avocado",
    calories: 240,
    protein: 3,
    carbs: 28,
    fat: 14,
    saturated_fat: 3,
    cholesterol: 0,
    sodium: 15,
    fiber: 5,
    sugar: 18,
    serving_size: "1 cup",
    ingredients: "Avocado, Cocoa Powder, Maple Syrup, Vanilla, Coconut Cream",
    allergens: [],
    dietary_tags: ["vegan", "gluten-free", "dairy-free", "dessert"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "dinner",
    avg_rating: 4.5,
    review_count: 89
  },
  {
    dish_id: 64,
    name: "Vanilla Bean Crème Brûlée",
    description: "Silky vanilla custard with caramelized sugar crust",
    calories: 340,
    protein: 5,
    carbs: 32,
    fat: 22,
    saturated_fat: 13,
    cholesterol: 220,
    sodium: 65,
    fiber: 0,
    sugar: 28,
    serving_size: "1 ramekin",
    ingredients: "Heavy Cream, Egg Yolks, Sugar, Vanilla Bean",
    allergens: ["milk", "eggs"],
    dietary_tags: ["vegetarian", "gluten-free", "dessert"],
    contains_pork: false,
    venue_id: 3,
    venue_name: "Piedmont North",
    meal_type: "dinner",
    avg_rating: 4.8,
    review_count: 145
  },
  {
    dish_id: 65,
    name: "Cookies & Cream Ice Cream",
    description: "Creamy vanilla ice cream loaded with chocolate cookie chunks",
    calories: 280,
    protein: 4,
    carbs: 34,
    fat: 14,
    saturated_fat: 9,
    cholesterol: 55,
    sodium: 120,
    fiber: 1,
    sugar: 28,
    serving_size: "1 scoop",
    ingredients: "Cream, Milk, Sugar, Chocolate Cookies, Vanilla",
    allergens: ["milk", "wheat"],
    dietary_tags: ["vegetarian", "dessert"],
    contains_pork: false,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "dinner",
    avg_rating: 4.6,
    review_count: 234
  },
  {
    dish_id: 66,
    name: "Fresh Fruit Tart",
    description: "Buttery pastry crust filled with vanilla custard and topped with fresh seasonal fruits",
    calories: 290,
    protein: 4,
    carbs: 38,
    fat: 14,
    saturated_fat: 8,
    cholesterol: 85,
    sodium: 110,
    fiber: 2,
    sugar: 22,
    serving_size: "1 slice",
    ingredients: "Pastry Crust, Vanilla Custard, Strawberries, Kiwi, Blueberries, Apricot Glaze",
    allergens: ["milk", "eggs", "wheat"],
    dietary_tags: ["vegetarian", "dessert"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "dinner",
    avg_rating: 4.5,
    review_count: 112
  },
  // ==========================================
  // MEXICAN CUISINE
  // ==========================================
  {
    dish_id: 67,
    name: "Chicken Burrito Bowl",
    description: "Cilantro lime rice, black beans, grilled chicken, pico de gallo, guacamole, and sour cream",
    calories: 580,
    protein: 38,
    carbs: 52,
    fat: 24,
    saturated_fat: 8,
    cholesterol: 95,
    sodium: 890,
    fiber: 10,
    sugar: 4,
    serving_size: "14 oz bowl",
    ingredients: "Cilantro Lime Rice, Black Beans, Grilled Chicken, Pico de Gallo, Guacamole, Sour Cream, Cheese",
    allergens: ["milk"],
    dietary_tags: ["gluten-free", "high-protein", "mexican"],
    contains_pork: false,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "lunch",
    avg_rating: 4.7,
    review_count: 289
  },
  {
    dish_id: 68,
    name: "Carnitas Tacos",
    description: "Slow-braised pork with fresh onion, cilantro, and lime on corn tortillas",
    calories: 420,
    protein: 28,
    carbs: 32,
    fat: 22,
    saturated_fat: 8,
    cholesterol: 85,
    sodium: 680,
    fiber: 4,
    sugar: 2,
    serving_size: "3 tacos",
    ingredients: "Braised Pork Shoulder, Corn Tortillas, Onion, Cilantro, Lime, Salsa Verde",
    allergens: [],
    dietary_tags: ["gluten-free", "high-protein", "mexican"],
    contains_pork: true,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "dinner",
    avg_rating: 4.8,
    review_count: 198
  },
  {
    dish_id: 69,
    name: "Vegetarian Enchiladas",
    description: "Corn tortillas filled with black beans and cheese, topped with red enchilada sauce",
    calories: 480,
    protein: 18,
    carbs: 52,
    fat: 22,
    saturated_fat: 10,
    cholesterol: 45,
    sodium: 920,
    fiber: 8,
    sugar: 6,
    serving_size: "2 enchiladas",
    ingredients: "Corn Tortillas, Black Beans, Cheese, Red Enchilada Sauce, Sour Cream, Rice",
    allergens: ["milk"],
    dietary_tags: ["vegetarian", "gluten-free", "mexican"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "dinner",
    avg_rating: 4.5,
    review_count: 134
  },
  {
    dish_id: 70,
    name: "Shrimp Quesadilla",
    description: "Grilled flour tortilla with seasoned shrimp, cheese, peppers, and chipotle crema",
    calories: 520,
    protein: 32,
    carbs: 38,
    fat: 28,
    saturated_fat: 12,
    cholesterol: 165,
    sodium: 780,
    fiber: 3,
    sugar: 3,
    serving_size: "1 quesadilla",
    ingredients: "Flour Tortilla, Shrimp, Cheese Blend, Bell Peppers, Onions, Chipotle Crema",
    allergens: ["milk", "wheat", "shellfish"],
    dietary_tags: ["high-protein", "mexican"],
    contains_pork: false,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "lunch",
    avg_rating: 4.6,
    review_count: 167
  },
  {
    dish_id: 71,
    name: "Street Corn (Elote)",
    description: "Grilled corn on the cob with mayo, cotija cheese, chili powder, and lime",
    calories: 220,
    protein: 6,
    carbs: 28,
    fat: 12,
    saturated_fat: 3,
    cholesterol: 15,
    sodium: 340,
    fiber: 3,
    sugar: 6,
    serving_size: "1 ear",
    ingredients: "Corn, Mayo, Cotija Cheese, Chili Powder, Lime, Cilantro",
    allergens: ["milk", "eggs"],
    dietary_tags: ["vegetarian", "gluten-free", "mexican"],
    contains_pork: false,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "lunch",
    avg_rating: 4.7,
    review_count: 212
  },
  // ==========================================
  // JAMAICAN CUISINE
  // ==========================================
  {
    dish_id: 72,
    name: "Jerk Chicken",
    description: "Authentic Jamaican jerk-spiced grilled chicken with rice and peas",
    calories: 520,
    protein: 42,
    carbs: 38,
    fat: 22,
    saturated_fat: 6,
    cholesterol: 125,
    sodium: 820,
    fiber: 4,
    sugar: 3,
    serving_size: "8 oz with sides",
    ingredients: "Chicken Thighs, Jerk Seasoning, Scotch Bonnet Peppers, Allspice, Rice, Kidney Beans, Coconut Milk",
    allergens: [],
    dietary_tags: ["gluten-free", "high-protein", "jamaican", "spicy"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "dinner",
    avg_rating: 4.9,
    review_count: 267
  },
  {
    dish_id: 73,
    name: "Oxtail Stew",
    description: "Slow-braised oxtail in rich gravy with butter beans, served with rice",
    calories: 580,
    protein: 38,
    carbs: 42,
    fat: 28,
    saturated_fat: 10,
    cholesterol: 95,
    sodium: 720,
    fiber: 6,
    sugar: 4,
    serving_size: "10 oz",
    ingredients: "Oxtail, Butter Beans, Tomatoes, Thyme, Scotch Bonnet, Rice",
    allergens: [],
    dietary_tags: ["gluten-free", "high-protein", "jamaican"],
    contains_pork: false,
    venue_id: 3,
    venue_name: "Piedmont North",
    meal_type: "dinner",
    avg_rating: 4.8,
    review_count: 189
  },
  {
    dish_id: 74,
    name: "Jamaican Beef Patty",
    description: "Flaky golden pastry filled with seasoned ground beef and spices",
    calories: 380,
    protein: 14,
    carbs: 38,
    fat: 20,
    saturated_fat: 8,
    cholesterol: 45,
    sodium: 580,
    fiber: 2,
    sugar: 2,
    serving_size: "1 patty",
    ingredients: "Flaky Pastry, Ground Beef, Curry, Thyme, Scotch Bonnet, Onions",
    allergens: ["wheat"],
    dietary_tags: ["jamaican", "spicy"],
    contains_pork: false,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "lunch",
    avg_rating: 4.6,
    review_count: 178
  },
  {
    dish_id: 75,
    name: "Ackee and Saltfish",
    description: "Jamaica's national dish - ackee fruit sautéed with salted codfish, onions, and peppers",
    calories: 320,
    protein: 24,
    carbs: 12,
    fat: 22,
    saturated_fat: 4,
    cholesterol: 65,
    sodium: 890,
    fiber: 2,
    sugar: 3,
    serving_size: "6 oz",
    ingredients: "Ackee, Salted Codfish, Onions, Tomatoes, Scotch Bonnet, Thyme",
    allergens: ["fish"],
    dietary_tags: ["gluten-free", "high-protein", "jamaican"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "breakfast",
    avg_rating: 4.5,
    review_count: 89
  },
  {
    dish_id: 76,
    name: "Curry Goat",
    description: "Tender goat meat slow-cooked in Caribbean curry with potatoes",
    calories: 480,
    protein: 36,
    carbs: 24,
    fat: 28,
    saturated_fat: 10,
    cholesterol: 95,
    sodium: 680,
    fiber: 3,
    sugar: 2,
    serving_size: "8 oz",
    ingredients: "Goat Meat, Curry Powder, Potatoes, Thyme, Scotch Bonnet, Garlic",
    allergens: [],
    dietary_tags: ["gluten-free", "high-protein", "jamaican", "halal"],
    contains_pork: false,
    venue_id: 3,
    venue_name: "Piedmont North",
    meal_type: "dinner",
    avg_rating: 4.7,
    review_count: 156
  },
  // ==========================================
  // AFRICAN CUISINE
  // ==========================================
  {
    dish_id: 77,
    name: "Jollof Rice with Chicken",
    description: "West African one-pot rice dish with tomatoes, peppers, and grilled chicken",
    calories: 520,
    protein: 32,
    carbs: 58,
    fat: 18,
    saturated_fat: 4,
    cholesterol: 85,
    sodium: 680,
    fiber: 4,
    sugar: 6,
    serving_size: "12 oz",
    ingredients: "Rice, Tomatoes, Bell Peppers, Onions, Grilled Chicken, African Spices",
    allergens: [],
    dietary_tags: ["gluten-free", "high-protein", "african", "halal"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "dinner",
    avg_rating: 4.9,
    review_count: 234
  },
  {
    dish_id: 78,
    name: "Nigerian Suya",
    description: "Spicy grilled beef skewers with suya spice blend, served with onions and tomatoes",
    calories: 380,
    protein: 35,
    carbs: 8,
    fat: 24,
    saturated_fat: 8,
    cholesterol: 85,
    sodium: 620,
    fiber: 2,
    sugar: 3,
    serving_size: "4 skewers",
    ingredients: "Beef Sirloin, Suya Spice (Peanuts, Ginger, Cayenne), Onions, Tomatoes",
    allergens: ["peanuts"],
    dietary_tags: ["gluten-free", "high-protein", "african", "spicy", "keto"],
    contains_pork: false,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "dinner",
    avg_rating: 4.8,
    review_count: 178
  },
  {
    dish_id: 79,
    name: "Ethiopian Doro Wat",
    description: "Spicy Ethiopian chicken stew with berbere spices, served with injera bread",
    calories: 450,
    protein: 34,
    carbs: 32,
    fat: 22,
    saturated_fat: 6,
    cholesterol: 145,
    sodium: 720,
    fiber: 4,
    sugar: 4,
    serving_size: "10 oz",
    ingredients: "Chicken, Berbere Spice, Onions, Tomatoes, Hard Boiled Eggs, Injera",
    allergens: ["eggs"],
    dietary_tags: ["high-protein", "african", "spicy"],
    contains_pork: false,
    venue_id: 3,
    venue_name: "Piedmont North",
    meal_type: "dinner",
    avg_rating: 4.7,
    review_count: 145
  },
  {
    dish_id: 80,
    name: "Moroccan Lamb Tagine",
    description: "Slow-cooked lamb with apricots, almonds, and warm spices over couscous",
    calories: 520,
    protein: 32,
    carbs: 48,
    fat: 22,
    saturated_fat: 8,
    cholesterol: 95,
    sodium: 580,
    fiber: 5,
    sugar: 18,
    serving_size: "10 oz",
    ingredients: "Lamb, Apricots, Almonds, Cinnamon, Cumin, Coriander, Couscous",
    allergens: ["wheat", "tree_nuts"],
    dietary_tags: ["high-protein", "african", "halal"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "dinner",
    avg_rating: 4.8,
    review_count: 167
  },
  {
    dish_id: 81,
    name: "Fufu with Egusi Soup",
    description: "Traditional West African pounded yam with melon seed soup and assorted meats",
    calories: 580,
    protein: 28,
    carbs: 62,
    fat: 26,
    saturated_fat: 6,
    cholesterol: 75,
    sodium: 720,
    fiber: 6,
    sugar: 4,
    serving_size: "12 oz",
    ingredients: "Pounded Yam, Egusi (Melon Seeds), Palm Oil, Spinach, Beef, Stockfish",
    allergens: ["fish"],
    dietary_tags: ["gluten-free", "high-protein", "african"],
    contains_pork: false,
    venue_id: 3,
    venue_name: "Piedmont North",
    meal_type: "dinner",
    avg_rating: 4.6,
    review_count: 112
  },
  {
    dish_id: 82,
    name: "South African Bobotie",
    description: "Spiced minced meat bake with egg topping, served with yellow rice and chutney",
    calories: 480,
    protein: 28,
    carbs: 38,
    fat: 24,
    saturated_fat: 10,
    cholesterol: 165,
    sodium: 620,
    fiber: 3,
    sugar: 12,
    serving_size: "10 oz",
    ingredients: "Ground Beef, Curry, Raisins, Almonds, Eggs, Milk, Yellow Rice, Chutney",
    allergens: ["milk", "eggs", "tree_nuts"],
    dietary_tags: ["high-protein", "african"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "dinner",
    avg_rating: 4.5,
    review_count: 89
  },
  // ==========================================
  // COMFORT FOOD / SOUL FOOD
  // ==========================================
  {
    dish_id: 83,
    name: "Southern Fried Chicken",
    description: "Crispy buttermilk-brined fried chicken with honey butter",
    calories: 580,
    protein: 42,
    carbs: 28,
    fat: 34,
    saturated_fat: 10,
    cholesterol: 165,
    sodium: 920,
    fiber: 1,
    sugar: 4,
    serving_size: "2 pieces",
    ingredients: "Chicken, Buttermilk, Flour, Paprika, Garlic, Honey Butter",
    allergens: ["milk", "wheat"],
    dietary_tags: ["high-protein", "comfort-food"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "dinner",
    avg_rating: 4.9,
    review_count: 312
  },
  {
    dish_id: 84,
    name: "Mac and Cheese",
    description: "Creamy four-cheese macaroni baked to golden perfection",
    calories: 480,
    protein: 18,
    carbs: 48,
    fat: 26,
    saturated_fat: 14,
    cholesterol: 75,
    sodium: 780,
    fiber: 2,
    sugar: 4,
    serving_size: "8 oz",
    ingredients: "Elbow Pasta, Cheddar, Gruyere, Cream Cheese, Parmesan, Butter, Milk",
    allergens: ["milk", "wheat"],
    dietary_tags: ["vegetarian", "comfort-food"],
    contains_pork: false,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "lunch",
    avg_rating: 4.7,
    review_count: 278
  },
  {
    dish_id: 85,
    name: "Chicken and Waffles",
    description: "Crispy fried chicken on Belgian waffles with maple syrup and hot honey",
    calories: 720,
    protein: 38,
    carbs: 68,
    fat: 34,
    saturated_fat: 12,
    cholesterol: 145,
    sodium: 920,
    fiber: 2,
    sugar: 28,
    serving_size: "1 plate",
    ingredients: "Fried Chicken, Belgian Waffles, Maple Syrup, Hot Honey, Butter",
    allergens: ["milk", "wheat", "eggs"],
    dietary_tags: ["high-protein", "comfort-food"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "breakfast",
    avg_rating: 4.8,
    review_count: 234
  },
  {
    dish_id: 86,
    name: "Shrimp and Grits",
    description: "Creamy stone-ground grits topped with sautéed shrimp in garlic butter sauce",
    calories: 520,
    protein: 32,
    carbs: 42,
    fat: 26,
    saturated_fat: 12,
    cholesterol: 195,
    sodium: 820,
    fiber: 2,
    sugar: 2,
    serving_size: "10 oz",
    ingredients: "Stone Ground Grits, Shrimp, Garlic, Butter, Cream, Green Onions",
    allergens: ["shellfish", "milk"],
    dietary_tags: ["gluten-free", "high-protein", "comfort-food"],
    contains_pork: false,
    venue_id: 1,
    venue_name: "Patton Hall",
    meal_type: "breakfast",
    avg_rating: 4.8,
    review_count: 198
  },
  {
    dish_id: 87,
    name: "BBQ Pulled Pork Sandwich",
    description: "Slow-smoked pulled pork with tangy BBQ sauce on brioche bun with coleslaw",
    calories: 620,
    protein: 34,
    carbs: 52,
    fat: 32,
    saturated_fat: 10,
    cholesterol: 95,
    sodium: 1120,
    fiber: 3,
    sugar: 22,
    serving_size: "1 sandwich",
    ingredients: "Pulled Pork, BBQ Sauce, Brioche Bun, Coleslaw",
    allergens: ["wheat", "eggs"],
    dietary_tags: ["high-protein", "comfort-food"],
    contains_pork: true,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "lunch",
    avg_rating: 4.7,
    review_count: 189
  },
  // ==========================================
  // ASIAN CUISINE
  // ==========================================
  {
    dish_id: 88,
    name: "Pad Thai",
    description: "Classic Thai rice noodles with shrimp, peanuts, bean sprouts, and lime",
    calories: 480,
    protein: 22,
    carbs: 58,
    fat: 18,
    saturated_fat: 3,
    cholesterol: 125,
    sodium: 820,
    fiber: 3,
    sugar: 12,
    serving_size: "12 oz",
    ingredients: "Rice Noodles, Shrimp, Eggs, Peanuts, Bean Sprouts, Tamarind, Fish Sauce, Lime",
    allergens: ["shellfish", "peanuts", "eggs", "fish"],
    dietary_tags: ["gluten-free", "thai"],
    contains_pork: false,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "dinner",
    avg_rating: 4.7,
    review_count: 234
  },
  {
    dish_id: 89,
    name: "Beef Pho",
    description: "Vietnamese noodle soup with rare beef, herbs, bean sprouts, and rich bone broth",
    calories: 420,
    protein: 32,
    carbs: 48,
    fat: 12,
    saturated_fat: 4,
    cholesterol: 65,
    sodium: 1280,
    fiber: 2,
    sugar: 4,
    serving_size: "16 oz",
    ingredients: "Rice Noodles, Beef Slices, Bone Broth, Star Anise, Cinnamon, Basil, Bean Sprouts, Hoisin",
    allergens: [],
    dietary_tags: ["gluten-free", "high-protein", "vietnamese"],
    contains_pork: false,
    venue_id: 3,
    venue_name: "Piedmont North",
    meal_type: "lunch",
    avg_rating: 4.8,
    review_count: 198
  },
  {
    dish_id: 90,
    name: "General Tso's Chicken",
    description: "Crispy chicken in sweet and spicy sauce with broccoli over steamed rice",
    calories: 580,
    protein: 28,
    carbs: 62,
    fat: 24,
    saturated_fat: 5,
    cholesterol: 85,
    sodium: 1080,
    fiber: 3,
    sugar: 28,
    serving_size: "12 oz",
    ingredients: "Chicken Breast, Sweet Chili Sauce, Broccoli, Rice, Ginger, Garlic",
    allergens: ["soy", "wheat"],
    dietary_tags: ["chinese", "spicy"],
    contains_pork: false,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "dinner",
    avg_rating: 4.5,
    review_count: 256
  },
  {
    dish_id: 91,
    name: "Sushi Combo Platter",
    description: "Chef's selection of nigiri, maki rolls, and sashimi with wasabi and ginger",
    calories: 380,
    protein: 28,
    carbs: 42,
    fat: 12,
    saturated_fat: 2,
    cholesterol: 45,
    sodium: 680,
    fiber: 2,
    sugar: 8,
    serving_size: "12 pieces",
    ingredients: "Sushi Rice, Salmon, Tuna, Yellowtail, Nori, Cucumber, Avocado",
    allergens: ["fish", "soy"],
    dietary_tags: ["japanese", "high-protein"],
    contains_pork: false,
    venue_id: 3,
    venue_name: "Piedmont North",
    meal_type: "lunch",
    avg_rating: 4.7,
    review_count: 189
  },
  // ==========================================
  // LATE NIGHT / SNACKS
  // ==========================================
  {
    dish_id: 92,
    name: "Loaded Nachos",
    description: "Crispy tortilla chips loaded with cheese, jalapeños, sour cream, and guacamole",
    calories: 680,
    protein: 18,
    carbs: 58,
    fat: 42,
    saturated_fat: 18,
    cholesterol: 65,
    sodium: 1120,
    fiber: 6,
    sugar: 4,
    serving_size: "12 oz",
    ingredients: "Tortilla Chips, Cheese Blend, Jalapeños, Sour Cream, Guacamole, Pico de Gallo",
    allergens: ["milk"],
    dietary_tags: ["vegetarian", "gluten-free", "snack"],
    contains_pork: false,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "dinner",
    avg_rating: 4.6,
    review_count: 234
  },
  {
    dish_id: 93,
    name: "Mozzarella Sticks",
    description: "Golden fried mozzarella sticks with marinara dipping sauce",
    calories: 420,
    protein: 18,
    carbs: 32,
    fat: 26,
    saturated_fat: 12,
    cholesterol: 55,
    sodium: 720,
    fiber: 2,
    sugar: 4,
    serving_size: "6 sticks",
    ingredients: "Mozzarella Cheese, Breadcrumbs, Italian Herbs, Marinara Sauce",
    allergens: ["milk", "wheat"],
    dietary_tags: ["vegetarian", "snack"],
    contains_pork: false,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "dinner",
    avg_rating: 4.5,
    review_count: 178
  },
  {
    dish_id: 94,
    name: "Chicken Tenders & Fries",
    description: "Crispy chicken tenders with seasoned fries and honey mustard",
    calories: 680,
    protein: 32,
    carbs: 58,
    fat: 36,
    saturated_fat: 8,
    cholesterol: 95,
    sodium: 1080,
    fiber: 4,
    sugar: 6,
    serving_size: "8 oz",
    ingredients: "Chicken Tenders, Seasoned Fries, Honey Mustard, BBQ Sauce",
    allergens: ["wheat", "eggs"],
    dietary_tags: ["high-protein", "snack"],
    contains_pork: false,
    venue_id: 2,
    venue_name: "The Commons",
    meal_type: "dinner",
    avg_rating: 4.4,
    review_count: 267
  }
];

// Allergen definitions matching Nutrislice
export const allergenTypes = [
  { id: "eggs", label: "Egg", icon: "🥚" },
  { id: "milk", label: "Milk", icon: "🥛" },
  { id: "wheat", label: "Wheat", icon: "🌾" },
  { id: "soy", label: "Soy", icon: "🫘" },
  { id: "peanuts", label: "Peanuts", icon: "🥜" },
  { id: "tree_nuts", label: "Tree Nuts", icon: "🌰" },
  { id: "fish", label: "Fish", icon: "🐟" },
  { id: "shellfish", label: "Shellfish", icon: "🦐" },
  { id: "sesame", label: "Sesame", icon: "🌱" }
];

// Special diet definitions matching Nutrislice
export const specialDiets = [
  { id: "vegan", label: "Vegan", icon: "🌱" },
  { id: "vegetarian", label: "Vegetarian", icon: "🥬" },
  { id: "gluten-free", label: "Gluten Friendly", icon: "GF" },
  { id: "halal", label: "Halal", icon: "☪️" },
  { id: "kosher", label: "Kosher", icon: "✡️" },
  { id: "high-protein", label: "High Protein", icon: "💪" },
  { id: "high-fiber", label: "High Fiber", icon: "🥗" },
  { id: "low-carb", label: "Low Carb", icon: "🍞" },
  { id: "keto", label: "Keto", icon: "🥑" },
  { id: "dairy-free", label: "Dairy Free", icon: "🥛" },
  { id: "low-sodium", label: "Low Sodium", icon: "🧂" },
  { id: "nut-free", label: "Nut Free", icon: "🥜" }
];

// Helper function to get dish by ID
export function getDishById(id: number): Dish | undefined {
  return dishes.find(d => d.dish_id === id);
}

// Helper function to filter dishes
export function filterDishes(options: {
  venueId?: number;
  mealType?: string;
  allergens?: string[];
  diets?: string[];
  excludePork?: boolean;
  search?: string;
}): Dish[] {
  return dishes.filter(dish => {
    // Venue filter
    if (options.venueId && dish.venue_id !== options.venueId) return false;
    
    // Meal type filter
    if (options.mealType && dish.meal_type !== options.mealType) return false;
    
    // Allergen filter (exclude dishes with selected allergens)
    if (options.allergens && options.allergens.length > 0) {
      const hasAllergen = options.allergens.some(a => dish.allergens.includes(a));
      if (hasAllergen) return false;
    }
    
    // Diet filter (include only dishes with ALL selected diets)
    if (options.diets && options.diets.length > 0) {
      const hasDiet = options.diets.every(d => dish.dietary_tags.includes(d));
      if (!hasDiet) return false;
    }
    
    // Pork filter
    if (options.excludePork && dish.contains_pork) return false;
    
    // Search filter
    if (options.search) {
      const searchLower = options.search.toLowerCase();
      const matchesSearch = 
        dish.name.toLowerCase().includes(searchLower) ||
        dish.description.toLowerCase().includes(searchLower) ||
        dish.ingredients.toLowerCase().includes(searchLower);
      if (!matchesSearch) return false;
    }
    
    return true;
  });
}
